### ISSUE TITLE
Working with VirtualHostX

### ISSUE THREAD

**Issue by jasperrooduijn** [jeremycastelli/Wordpress-new-project-config#8]
This is really a time saver. Great work!
 
Small question, would it be possible adding the new project to VirtualHostX. We use the OSX built in apache server and therefor do not use MAMP. For making the virtual hostnames work we use VHX.

I would be wonderful if we could also automate this action.

**Comment by imacnu** [comment]
Hi,i have installed it and its cool, but when i try open index.php from mamp don't work, template is empty. Whats happening?. Thanks

**Comment by jeremycastelli** [comment]
Hey,
sorry for the late answer
Could you resolve your issue ?
if not I need more info about your problem.
But I want to say that I can't give you support on how to develop wordpress theme.
WNPC is just a way to accelerate your workflow on the beginning of each project
Thanks anyway for using WNPC
Best,
